deployment:
  tasks:
    - export DEPLOYPATH=/home/markzpwz/public_html/dds/
    - cd /home/markzpwz/repositories/DDS
    - /bin/rsync -av --delete --exclude '.git' --exclude '.cpanel.yml' ./ "${DEPLOYPATH}"
    - find ~/public_html/dds -type d -exec chmod 755 {} \;